# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'noloTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for noloTest
  pod 'Alamofire'
  pod 'Dollar'
  pod 'Kingfisher', '~> 5.0'
  pod 'SVProgressHUD'
  pod 'SwiftDate', '~> 5.0'
  pod 'SCLAlertView'
end
